"""Missions = curated card sequences."""

MISSIONS = [
    {
        "id": "space-101",
        "title": "Space Explorer Mission",
        "emoji": "🚀",
        "subject": "astronomy",
        "mascot": "zoomerroo",
        "totalCards": 5,
        "xpReward": 100,
        "estimatedMinutes": 7,
        "curriculum": "Year 5-6 Science",
        "cardIds": ["f3", "q1", "f10", "q9", "f16"],
    },
    {
        "id": "life-is-cells",
        "title": "Life is Cells",
        "emoji": "🧬",
        "subject": "biology",
        "mascot": "drSprout",
        "totalCards": 4,
        "xpReward": 80,
        "estimatedMinutes": 6,
        "curriculum": "Year 6-7 Science",
        "cardIds": ["f9", "f1", "f14", "d1"],
    },
    {
        "id": "forces-motion",
        "title": "Forces & Motion",
        "emoji": "⚡",
        "subject": "physics",
        "mascot": "sprouty",
        "totalCards": 5,
        "xpReward": 90,
        "estimatedMinutes": 8,
        "curriculum": "Year 5-6 Science",
        "cardIds": ["f2", "q5", "e2", "f11", "f17"],
    },
    {
        "id": "mini-ecosystem",
        "title": "Mini Ecosystem",
        "emoji": "🌿",
        "subject": "nature",
        "mascot": "sprouty",
        "totalCards": 4,
        "xpReward": 60,
        "estimatedMinutes": 5,
        "curriculum": "Year 2-4 Science",
        "cardIds": ["f5", "e3", "f12", "f15"],
    },
    {
        "id": "maths-in-nature",
        "title": "Maths in Nature",
        "emoji": "🧮",
        "subject": "maths",
        "mascot": "zoomerroo",
        "totalCards": 3,
        "xpReward": 70,
        "estimatedMinutes": 5,
        "curriculum": "Year 5-7 Maths",
        "cardIds": ["f7", "q4", "f19"],
    },
    {
        "id": "how-computers-think",
        "title": "How Computers Think",
        "emoji": "💻",
        "subject": "technology",
        "mascot": "zoomerroo",
        "totalCards": 4,
        "xpReward": 100,
        "estimatedMinutes": 7,
        "curriculum": "Year 6-8 Digital Tech",
        "cardIds": ["f6", "q6", "d2", "s5"],
    },
]
